### ISSUE TITLE
Shows information of the authenticated user and not of the queried user

### ISSUE THREAD

**Issue by infante91** [catalyst/moodle-block_dedication#102]
I am a Moodle administrator and I have encountered the following problem these days... After the last update of the 'Course dedication' plugin 2023112000.

When I try to download an Excel with the connections of a specific participant (View session duration report), it shows me the connections of the authenticated user instead of the consulted user.

Can you help me please? I have not touched any of the code since the last update 2023112000.

Thank you very much for your help.

**Comment by danmarsden** [comment]
Hi there - this sounds like a duplicate of #98  which has been fixed in the version you can download here from github but we haven't published a new version to the plugins db with this change yet - hopefully I'll get a chance to do that soon, otherwise feel free to download the version here in github and it should fix this for you!

**Comment by infante91** [comment]
> Hi there - this sounds like a duplicate of #98 which has been fixed in the version you can download here from github but we haven't published a new version to the plugins db with this change yet - hopefully I'll get a chance to do that soon, otherwise feel free to download the version here in github and it should fix this for you!

it worked! thank you very much!
